[package]
name = 'persistent-cache'
version = "0.0.0"
authors = ["Matthias Fauconneau <matthiass.fauconneau@gmail.com"]
edition =  "2018"
description = "Persistent cache using files"

[dependencies]
fehler = ''
anyhow = ''
log = ''
serde = ''
bincode = ''
lazy_static = ''
dirs = ''
